// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"bosh-vmrun-cpi/stemcell"
	"sync"
)

type FakeStemcellClient struct {
	CleanupStub        func()
	cleanupMutex       sync.RWMutex
	cleanupArgsForCall []struct {
	}
	ExtractOvfStub        func(string) (string, error)
	extractOvfMutex       sync.RWMutex
	extractOvfArgsForCall []struct {
		arg1 string
	}
	extractOvfReturns struct {
		result1 string
		result2 error
	}
	extractOvfReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStemcellClient) Cleanup() {
	fake.cleanupMutex.Lock()
	fake.cleanupArgsForCall = append(fake.cleanupArgsForCall, struct {
	}{})
	fake.recordInvocation("Cleanup", []interface{}{})
	fake.cleanupMutex.Unlock()
	if fake.CleanupStub != nil {
		fake.CleanupStub()
	}
}

func (fake *FakeStemcellClient) CleanupCallCount() int {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	return len(fake.cleanupArgsForCall)
}

func (fake *FakeStemcellClient) CleanupCalls(stub func()) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = stub
}

func (fake *FakeStemcellClient) ExtractOvf(arg1 string) (string, error) {
	fake.extractOvfMutex.Lock()
	ret, specificReturn := fake.extractOvfReturnsOnCall[len(fake.extractOvfArgsForCall)]
	fake.extractOvfArgsForCall = append(fake.extractOvfArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ExtractOvf", []interface{}{arg1})
	fake.extractOvfMutex.Unlock()
	if fake.ExtractOvfStub != nil {
		return fake.ExtractOvfStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.extractOvfReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStemcellClient) ExtractOvfCallCount() int {
	fake.extractOvfMutex.RLock()
	defer fake.extractOvfMutex.RUnlock()
	return len(fake.extractOvfArgsForCall)
}

func (fake *FakeStemcellClient) ExtractOvfCalls(stub func(string) (string, error)) {
	fake.extractOvfMutex.Lock()
	defer fake.extractOvfMutex.Unlock()
	fake.ExtractOvfStub = stub
}

func (fake *FakeStemcellClient) ExtractOvfArgsForCall(i int) string {
	fake.extractOvfMutex.RLock()
	defer fake.extractOvfMutex.RUnlock()
	argsForCall := fake.extractOvfArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStemcellClient) ExtractOvfReturns(result1 string, result2 error) {
	fake.extractOvfMutex.Lock()
	defer fake.extractOvfMutex.Unlock()
	fake.ExtractOvfStub = nil
	fake.extractOvfReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStemcellClient) ExtractOvfReturnsOnCall(i int, result1 string, result2 error) {
	fake.extractOvfMutex.Lock()
	defer fake.extractOvfMutex.Unlock()
	fake.ExtractOvfStub = nil
	if fake.extractOvfReturnsOnCall == nil {
		fake.extractOvfReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.extractOvfReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStemcellClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	fake.extractOvfMutex.RLock()
	defer fake.extractOvfMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStemcellClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ stemcell.StemcellClient = new(FakeStemcellClient)
