// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"bosh-esxi-cpi/govc"
	"sync"
)

type FakeGovcRunner struct {
	CliCommandStub        func(string, map[string]string, []string) (string, error)
	cliCommandMutex       sync.RWMutex
	cliCommandArgsForCall []struct {
		arg1 string
		arg2 map[string]string
		arg3 []string
	}
	cliCommandReturns struct {
		result1 string
		result2 error
	}
	cliCommandReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGovcRunner) CliCommand(arg1 string, arg2 map[string]string, arg3 []string) (string, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.cliCommandMutex.Lock()
	ret, specificReturn := fake.cliCommandReturnsOnCall[len(fake.cliCommandArgsForCall)]
	fake.cliCommandArgsForCall = append(fake.cliCommandArgsForCall, struct {
		arg1 string
		arg2 map[string]string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	fake.recordInvocation("CliCommand", []interface{}{arg1, arg2, arg3Copy})
	fake.cliCommandMutex.Unlock()
	if fake.CliCommandStub != nil {
		return fake.CliCommandStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.cliCommandReturns.result1, fake.cliCommandReturns.result2
}

func (fake *FakeGovcRunner) CliCommandCallCount() int {
	fake.cliCommandMutex.RLock()
	defer fake.cliCommandMutex.RUnlock()
	return len(fake.cliCommandArgsForCall)
}

func (fake *FakeGovcRunner) CliCommandArgsForCall(i int) (string, map[string]string, []string) {
	fake.cliCommandMutex.RLock()
	defer fake.cliCommandMutex.RUnlock()
	return fake.cliCommandArgsForCall[i].arg1, fake.cliCommandArgsForCall[i].arg2, fake.cliCommandArgsForCall[i].arg3
}

func (fake *FakeGovcRunner) CliCommandReturns(result1 string, result2 error) {
	fake.CliCommandStub = nil
	fake.cliCommandReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGovcRunner) CliCommandReturnsOnCall(i int, result1 string, result2 error) {
	fake.CliCommandStub = nil
	if fake.cliCommandReturnsOnCall == nil {
		fake.cliCommandReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.cliCommandReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGovcRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.cliCommandMutex.RLock()
	defer fake.cliCommandMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGovcRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ govc.GovcRunner = new(FakeGovcRunner)
