// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/micahyoung/bosh-govmomi-cpi/govc"
)

type FakeGovcConfig struct {
	EsxUrlStub        func() string
	esxUrlMutex       sync.RWMutex
	esxUrlArgsForCall []struct{}
	esxUrlReturns     struct {
		result1 string
	}
	esxUrlReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGovcConfig) EsxUrl() string {
	fake.esxUrlMutex.Lock()
	ret, specificReturn := fake.esxUrlReturnsOnCall[len(fake.esxUrlArgsForCall)]
	fake.esxUrlArgsForCall = append(fake.esxUrlArgsForCall, struct{}{})
	fake.recordInvocation("EsxUrl", []interface{}{})
	fake.esxUrlMutex.Unlock()
	if fake.EsxUrlStub != nil {
		return fake.EsxUrlStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.esxUrlReturns.result1
}

func (fake *FakeGovcConfig) EsxUrlCallCount() int {
	fake.esxUrlMutex.RLock()
	defer fake.esxUrlMutex.RUnlock()
	return len(fake.esxUrlArgsForCall)
}

func (fake *FakeGovcConfig) EsxUrlReturns(result1 string) {
	fake.EsxUrlStub = nil
	fake.esxUrlReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGovcConfig) EsxUrlReturnsOnCall(i int, result1 string) {
	fake.EsxUrlStub = nil
	if fake.esxUrlReturnsOnCall == nil {
		fake.esxUrlReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.esxUrlReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGovcConfig) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.esxUrlMutex.RLock()
	defer fake.esxUrlMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGovcConfig) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ govc.GovcConfig = new(FakeGovcConfig)
